### ISSUE TITLE
Error when create Channel

### ISSUE THREAD

**Issue by longtran84** [ecsoya/fabric-java-fabcar#2]
org.hyperledger.fabric.sdk.exception.TransactionException: Channel mychannel, send transaction failed on orderer OrdererClient{id: 4, channel: mychannel, name: orderer.example.com, url: grpc://localhost:7050}. Reason: Channel mychannel orderer orderer.example.com status returned failure code 400 (BAD_REQUEST) during orderer next
	at org.hyperledger.fabric.sdk.OrdererClient.sendTransaction(OrdererClient.java:236)
	at org.hyperledger.fabric.sdk.Orderer.sendTransaction(Orderer.java:164)
	at org.hyperledger.fabric.sdk.Channel.sendUpdateChannel(Channel.java:548)
	at org.hyperledger.fabric.sdk.Channel.<init>(Channel.java:245)
	at org.hyperledger.fabric.sdk.Channel.createNewInstance(Channel.java:338)
	at org.hyperledger.fabric.sdk.HFClient.newChannel(HFClient.java:222)
	at org.ecsoya.fabric.network.CreateChannel.main(CreateChannel.java:76)
Caused by: org.hyperledger.fabric.sdk.exception.TransactionException: Channel mychannel orderer orderer.example.com status returned failure code 400 (BAD_REQUEST) during orderer next
	at org.hyperledger.fabric.sdk.OrdererClient$1.onNext(OrdererClient.java:182)
	at org.hyperledger.fabric.sdk.OrdererClient$1.onNext(OrdererClient.java:174)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by longtran84** [comment]
./generate.sh: 16: ./generate.sh: cryptogen: not found
Failed to generate crypto material...
